server:
  port: 8080

spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: usuario-service
              uri: lb://MS-USUARIO
              predicates:
                - Path=/api/v1/usuarios/**

            - id: ms-sucursal
              uri: lb://MS-SUCURSAL
              predicates:
                - Path=/api/v1/sucursales/**

            - id: ubicacion-service
              uri: lb://MS-UBICACION
              predicates:
                - Path=/api/v1/ubicaciones/**

            - id: producto-service
              uri: lb://MS-PRODUCTO
              predicates:
                - Path=/api/v1/productos/**
                
            - id: venta-service
              uri: lb://MS-VENTA
              predicates:
                - Path=/api/v1/ventas/**

            - id: inventario-service
              uri: lb://MS-INVENTARIO
              predicates:
                - Path=/api/v1/inventarios/**

            - id: abastecimiento-service
              uri: lb://MS-ABASTECIMIENTO
              predicates:
                - Path=/api/v1/recepciones/**

                    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}